version: '3.7'
services:
  nlpaas:
    image: docker.lappsgrid.org/lappsgrid/nlpaas
    ports:
      - 8082:8080
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
